export const channelType = '__yacol__coroutine__type__'
export const pidString = '__yacol__coroutine__current__pid__'
export const corType = '__yacol__coroutine__handle__type__'
export const terminatedErrorType = '__yacol__terminated__error__type__'
export const runcBadCbArgs = '__yacol__runc__bad__cb__args__'
